<a href="https://colab.research.google.com/github/faizulhz/ProgrammingAssignment2/blob/master/ADABOOST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris


iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)


base_classifier = DecisionTreeClassifier(max_depth=1)


boosting_clf = AdaBoostClassifier(base_classifier, n_estimators=5, random_state=42)


boosting_clf.fit(X_train, y_train)


y_pred = boosting_clf.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Boosting Accuracy: {accuracy}')
print('Boosting Confusion Matrix:')
print(conf_matrix)


Boosting Accuracy: 0.9666666666666667
Boosting Confusion Matrix:
[[23  0  0]
 [ 0 18  1]
 [ 0  1 17]]
