<a href="https://colab.research.google.com/github/faizulhz/ProgrammingAssignment2/blob/master/BAGGINGCOMPLETE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris


iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


base_classifier = DecisionTreeClassifier()


bagging_clf = BaggingClassifier(base_classifier, n_estimators=10, random_state=42)


bagging_clf.fit(X_train, y_train)


y_pred = bagging_clf.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Bagging Accuracy: {accuracy}')
print('Bagging Confusion Matrix:')
print(conf_matrix)


Bagging Accuracy: 1.0
Bagging Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris


iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


base_classifier = SVC(kernel='linear', probability=True)


bagging_clf = BaggingClassifier(base_classifier, n_estimators=10, random_state=42)


bagging_clf.fit(X_train, y_train)


y_pred = bagging_clf.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Bagging Accuracy: {accuracy}')
print('Bagging Confusion Matrix:')
print(conf_matrix)


Bagging Accuracy: 1.0
Bagging Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
